export const mockTeams = [
  {
    id: '1',
    name: 'Alpha Squad',
    organization: 'Technology',
    location: 'NA',
    team_lead: {
      name: 'Sarah Chen',
      email: 'sarah.chen@example.com',
      password: 'hashed_placeholder',
      location: 'NA',
      position: 'Engineering Manager',
    },
  },
  {
    id: '2',
    name: 'Horizon Team',
    organization: 'Credit Cards',
    location: 'EU',
    team_lead: {
      name: 'Marcus Williams',
      email: 'marcus.williams@example.com',
      password: 'hashed_placeholder',
      location: 'EU',
      position: 'Lead Designer',
    },
  },
  {
    id: '3',
    name: 'Apex Group',
    organization: 'Private Banking',
    location: 'APAC',
    team_lead: {
      name: 'Priya Patel',
      email: 'priya.patel@example.com',
      password: 'hashed_placeholder',
      location: 'APAC',
      position: 'Data Scientist',
    },
  },
  {
    id: '4',
    name: 'Nova Unit',
    organization: 'Technology',
    location: 'LATAM',
    team_lead: {
      name: 'James Okafor',
      email: 'james.okafor@example.com',
      password: 'hashed_placeholder',
      location: 'LATAM',
      position: 'Senior iOS Engineer',
    },
  },
];

export const mockIndividuals = [
  {
    id: '1',
    name: 'Sarah Chen',
    email: 'sarah.chen@example.com',
    password: 'hashed_placeholder',
    position: 'Engineering Manager',
    location: 'NA',
  },
  {
    id: '2',
    name: 'Marcus Williams',
    email: 'marcus.williams@example.com',
    password: 'hashed_placeholder',
    position: 'Lead Designer',
    location: 'EU',
  },
  {
    id: '3',
    name: 'Priya Patel',
    email: 'priya.patel@example.com',
    password: 'hashed_placeholder',
    position: 'Data Scientist',
    location: 'APAC',
  },
  {
    id: '4',
    name: 'James Okafor',
    email: 'james.okafor@example.com',
    password: 'hashed_placeholder',
    position: 'Senior iOS Engineer',
    location: 'LATAM',
  },
  {
    id: '5',
    name: 'Elena Rodriguez',
    email: 'elena.rodriguez@example.com',
    password: 'hashed_placeholder',
    position: 'Backend Engineer',
    location: 'NA',
  },
  {
    id: '6',
    name: 'Tom Nakamura',
    email: 'tom.nakamura@example.com',
    password: 'hashed_placeholder',
    position: 'DevOps Engineer',
    location: 'APAC',
  },
];
